name: Update Zenn Feed

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Zenn Feed
    steps:
    - uses: actions/checkout@v4
    - uses: sarisia/actions-readme-feed@v1
      name: readme feed
      with:
        url: 'https://zenn.dev/hrtk92/feed'
        file: 'README.md'
        locale: 'ja-JP'
        format: '- <img src="./img/zenn.png" width="16" /> [${title}](${url}?utm_source=github)'
    - name: 'push commit'
      run: |
        if ! git diff --exit-code --quiet
        then
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Update zenn feed'
          git push
        fi
